# Generated by Django 5.0.4 on 2024-08-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="teachers/"
            ),
        ),
    ]
