# Generated by Django 5.0.4 on 2024-05-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='short',
        ),
    ]
