# Generated by Django 5.0.4 on 2024-07-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="capacity",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
