# Generated by Django 5.0.4 on 2024-07-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_alter_classroom_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="profile/"
            ),
        ),
    ]
