# Generated by Django 5.0.4 on 2024-07-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_alter_teacher_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="division",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("name", "division")},
        ),
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.CheckConstraint(
                check=models.Q(("division__in", "ABCDEFGHIJKLMNOPQRSTUVWXYZ")),
                name="valid_division",
            ),
        ),
    ]
