# Generated by Django 5.0.4 on 2024-07-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0006_alter_classroom_division_alter_classroom_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="division",
            field=models.CharField(max_length=1),
        ),
    ]
