# Generated by Django 5.0.4 on 2024-08-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="email address"
            ),
        ),
    ]
