# Generated by Django 5.0.4 on 2024-08-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0002_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
