# Generated by Django 5.0.4 on 2024-08-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
    ]
