# Generated by Django 5.0.4 on 2024-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_bus',
            field=models.BooleanField(default=False),
        ),
    ]
