# Generated by Django 5.0.4 on 2024-08-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_remove_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="students/"
            ),
        ),
    ]
