# Generated by Django 5.0.4 on 2024-05-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbus', '0001_initial'),
        ('student', '0002_student_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schoolbus.buspoint'),
        ),
        migrations.AddField(
            model_name='student',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schoolbus.route'),
        ),
    ]
