# Generated by Django 5.0.4 on 2024-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_is_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbusservice',
            name='annual_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
