# Generated by Django 5.0.4 on 2024-06-10 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_payment_delete_buspayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="bus_service",
        ),
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="student.student",
            ),
            preserve_default=False,
        ),
    ]
