# Generated by Django 5.0.4 on 2024-06-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_remove_payment_bus_service_payment_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="balance_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
