# Generated by Django 5.0.4 on 2024-08-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolbus", "0003_remove_route_students"),
        ("student", "0005_remove_student_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="schoolbus.route",
            ),
        ),
    ]
