# Generated by Django 5.0.4 on 2024-07-20 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolbus", "0001_initial"),
        ("student", "0006_payment_balance_amount_payment_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="route",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="schoolbus.route",
            ),
            preserve_default=False,
        ),
    ]
