# Generated by Django 5.0.4 on 2024-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_student_route"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.AddField(
            model_name="student",
            name="house_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="pincode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="post_office",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
