# Generated by Django 5.0.4 on 2024-07-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_remove_student_address_student_house_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="route",
        ),
    ]
